name: Build Go Project

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Extract Go version from go.mod
      id: go_version
      run: |
        echo "GO_VERSION=$(grep -E '^go [0-9]+\.[0-9]+$' go.mod | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.go_version.outputs.GO_VERSION }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Go Vet
      run: go vet ./...
      
    - name: Go Fmt Check
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted correctly:"
          gofmt -l .
          exit 1
        fi